- name: Printing the environment​ variable in Ansible (local env)
  debug:
    msg: "{{ lookup('env','HOME') }}"

- name: Printing all the environment​ variables in Ansible
  debug:
    msg: "{{ ansible_env }}"

- name: Printing a particular environment variable
  debug:
    msg: "{{ ansible_env.LANG}}"
