---
- name: Install Packages
  become: true
  apt: name="{{item}}" state=present update_cache=yes
  with_items:
    - vim
    - curl
    - stow
    - git
    - htop
    - tmux
    - youtube-dl
    - moc
    - network-manager-openvpn
    - network-manager-openvpn-gnome
    - xfonts-terminus
    - scrot
    - nautilus-dropbox
    - mpv
    - tree
    - nmap
    - vagrant
    - tilix
    - python3-setuptools
    - python3-pip
    - zsh
    - jq
    - imagemagick
    #- gnome-tweaks

# Install Monaco fonts
- name: Create font directory (Monaco)
  become: true
  file:
    path: /usr/share/fonts/truetype/ttf-monaco
    state: directory
- name: Download Monaco fonts
  become: true
  get_url:
    url: http://www.gringod.com/wp-upload/software/Fonts/Monaco_Linux.ttf
    dest: /usr/share/fonts/truetype/ttf-monaco/
- name: Install Monaco fonts
  become: true
  command: mkfontdir && cd /usr/share/fonts/truetype/ && fc-cache
