---
- hosts: vagrant-testing
  become: yes
  vars:
    packages:
      - vim
      - curl
      - stow
      - git
      - htop
      - tmux
      - youtube-dl
      - moc
      - network-manager-openvpn
      - network-manager-openvpn-gnome
      - xfonts-terminus
      - scrot
      - nautilus-dropbox
      - mpv
      - tree
      - nmap
      - vagrant
      - tilix
      - python3-setuptools
      - python3-pip
      - zsh
      - jq
      - imagemagick
      - gnome-tweaks
  
  tasks:
    - name: UPDATE APT CACHE
      apt: 
        update_cache: yes
    - name: UPDATE INSTALLED PACKAGES
      apt:
        upgrade: safe
    - name: INSTALL PACKAGES
      apt: name={{item}} state=present
      with_items: "{{packages}}"
    - name: CLONE DOTFILES REPO
      git:
        repo: https://github.com/alexeastaugh/dotfiles.git
        dest: /tmp/dotfiles/
        version: master
    - name: SYNC DOTFILES WITH STOW
      shell: stow bash
      args:
        chdir: /tmp/dotfiles
