---
- name: Install Packages
  become: true
  apt: 
    force_apt_get: yes
    name: [
      'vim', 
      'curl', 
      'stow', 
      'git', 
      'htop', 
      'tmux', 
      'youtube-dl', 
      'moc', 
      'network-manager-openvpn', 
      'network-manager-openvpn-gnome', 
      'xfonts-terminus', 
      'scrot', 
      'nautilus-dropbox',
      'mpv', 
      'tree', 
      'nmap', 
      'vagrant', 
      'tilix', 
      'python3-setuptools', 
      'python3-pip', 
      'zsh', 
      'jq', 
      'imagemagick']